version: "{build}"
skip_tags: true
clone_folder: c:\gopath\src\github.com\lifei6671\go-git-webhook
clone_depth: 1

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.8

build: false
deploy: false

install:
  - go build -v

notifications:
  - provider: Email
    to:
      - lifei6671@163.com
    on_build_success: false